server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: hospitalizationinfo
          uri: http://localhost:8082
          predicates:
            - Path=/hospitalizationInfos/**, 
        - id: hospital
          uri: http://localhost:8083
          predicates:
            - Path=/hospitals/**, 
        - id: patient
          uri: http://localhost:8084
          predicates:
            - Path=/patients/**, 
        - id: reservation
          uri: http://localhost:8085
          predicates:
            - Path=/reservations/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: hospitalizationinfo
          uri: http://hospitalizationinfo:8080
          predicates:
            - Path=/hospitalizationInfos/**, 
        - id: hospital
          uri: http://hospital:8080
          predicates:
            - Path=/hospitals/**, 
        - id: patient
          uri: http://patient:8080
          predicates:
            - Path=/patients/**, 
        - id: reservation
          uri: http://reservation:8080
          predicates:
            - Path=/reservations/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
